### ISSUE TITLE
Frame with no bounding box

### ISSUE THREAD

**Issue by farhad-dalirani** [MrGolden1/sort-python#8]
Hi,

In the code, it was assumed all frames contain at least one bounding box. If an object detector can not detect any object in a frame, .run() will face a problem. If we do not call .run() for empty frames, the aging will not happen properly. 

Am I right?

Best,

**Comment by MrGolden1** [comment]
Hello,

You're right in your approach. It's necessary to call .run() on frames without detections to maintain proper aging. For these frames, just pass an empty NumPy array with shape (0, 4). This ensures consistent aging process across all frames.

Best regards,

**Comment by farhad-dalirani** [comment]
Hi,

Thank you for your answer.

Best,
Farhad
